Fix error since using stdenv
error: The `env` attribute set cannot contain any attributes passed to
derivation. The following attributes are overlapping:
         - COQBIN: in `env`: "/nix/store/kfdvs2fxfg2rwrg8ixnl5qyfp8w33kbf-coq-dev/bin/"; in derivation arguments: ""